development:
  adapter: postgresql
  database: highscore_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: highscore_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: highscore_production
  pool: 5
  timeout: 5000
